movieblog/blog/urls.py
# importing django routing libraries
from . import views
from django.urls import path, include
from .views import *
# from .feeds import blogFeed

urlpatterns = [
	# home page
	path('', views.postslist.as_view(), name='posts'),
	# route for posts
	path('<slug:slug>/', views.postdetail.as_view(), name='post_detail'),
]

movieblog/movieblog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
 
urlpatterns = [
    # urls handling admin route
    path('admin/', admin.site.urls),
    # urls handling blog routes
    path('', include('blog.urls')),
]

movieblog/blog/models.py
# Create your models here.
# importing django models and users
from django.db import models
from django.contrib.auth.models import User

STATUS = (
	(0,"Draft"),
	(1,"Publish"),
	(2, "Delete")
)

# creating an django model class
class posts(models.Model):
	# title field using charfield constraint with unique constraint
	title = models.CharField(max_length=200, unique=True)
	# slug field auto populated using title with unique constraint
	slug = models.SlugField(max_length=200, unique=True)
	# author field populated using users database
	author = models.ForeignKey(User, on_delete= models.CASCADE)
	# and date time fields automatically populated using system time
	updated_on = models.DateTimeField(auto_now= True)
	created_on = models.DateTimeField()
	# content field to store our post
	content = models.TextField()
	# meta description for SEO benefits
	metades = models.CharField(max_length=300, default="new post")
	# status of post
	status = models.IntegerField(choices=STATUS, default=0)

	# meta for the class
	class Meta:
		ordering = ['-created_on']
	# used while managing models from terminal
	def __str__(self):
		return self.title

movieblog/blog/views.py
# Create your views here.
# importing models and libraries
from django.shortcuts import render
from .models import posts
from django.views import generic
from django.views.decorators.http import require_GET
from django.http import HttpResponse

# class based views for posts
class postslist(generic.ListView):
	# queryset = posts.objects.filter().order_by('-created_on')
	queryset = posts.objects.all()
	template_name = 'home.html'
	paginate_by = 4

# class based view for each post
class postdetail(generic.DetailView):
	model = posts
	template_name = "individual.html"

movieblog/blog/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- will be replaced with meta content -->
    {% block metatags %}{% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <style>
        html,
        body {
            height: 100%;
        }

        body {
            font-family: sans-serif;
            font-size: 18px;
            background-color: #fdfdfd;
            display: flex;
            flex-direction: column;
        }

        #nofooter {
            flex: 1 0 auto;
        }

        darkbtn {
            color: #66ff99;
        }

        .dark-mode {
            background-color: black;
            color: white;
        }

        #foot {
            flex-shrink: 0;
            font-family: sans-serif;
            background-color: #BDFFD3;
            color: #00308F;
            bottom: 0px;
            width: 100%;
        }

        .card-group,
        .card,
        .card-footer,
        .card-body {
            border: none;
        }
    </style>
</head>

<body>
    <div id="bodydiv">
        <div id="nofooter">
            <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="topnav">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'posts' %}">
                        <img src="/static/logo.jpg" width="30" height="30"
                            class="d-inline-block rounded align-top" alt="logo" loading="lazy">
                        Cinema Blog
                    </a>
                    <div class="nav justify-content-end">
                        <div class="d-inline"><a class="nav-link text-black font-weight-bold"
                                href="{% url 'posts'%}">Posts</a></div>
                    </div>
                </div>
            </nav>
            <!-- will be replaced with post content -->
            {% block content %}
            {% endblock content %}
        </div>
    </div>
</body>

</html>

movieblog/blog/templates/home.html
{% extends "base.html" %}
{% block metatags %}
<title>Movie Blog</title>
{% endblock %}
{% block content %}
<style type="text/css">
    body {
        font-family: 'Raleway', sans-serif;
    }

    .head_text {
        color: white;
    }

    .h1,
    h4 {
        font-family: 'Raleway', sans-serif;
    }

    #mainhome {
        text-align: center;
    }
</style>
<header class="jumbotron" style="background-color: burlywood; color: #00308F;">
    <div class="container">
        <p class="h1"> Movie <strong>Blog</strong></p>
    </div>
</header>
<div class="container">
    <div class="row">
        <div class="col-md-8 mt-3 left">
            {% for post in posts_list %}
            <div class="shadow-none card mb-4" id="newsfeed">
                <div class="card-body">
                    <h3 class="card-title">{{ post.title }}</h3>
                    <p class="card-text text-muted h6">
                            | {{ post.created_on}} </p>
                    <p class="card-text">{{post.metades }}</p>
                    <span><a href="{% url 'post_detail' post.slug %}" class="btn btn-outline-primary">Read More
                            →</a></span><span>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% if is_paginated %}
<nav aria-label="Page navigation container"></nav>
<ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-info"
            style="font-family: sans-serif;">« PREV </a></li>
    {% endif %}
    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-info" style="font-family: sans-serif;">
            NEXT »</a></li>

    {% endif %}
</ul>
{% endif %}
{%endblock%}

movieblog/blog/templates/individual.html
{% extends 'base.html' %}
{% block content %}
<style type="text/css">
    #container img {
        border-radius: 29px;
        width: 100%;
        height: 360px;
        opacity: 0.7;
        align-content: center;
    }

    #container img {
        opacity: 1.0;
    }

    a {
        text-align: center;
        text-decoration: none;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-6 left">
            <h1 class="card-title">{% block title %} {{ object.title }} {% endblock title %}</h1>
            <p class=" text-muted">{{ object.author.first_name }} {{ object.author.last_name }} |{{ object.created_on }}
            </p>





            <p class="card-text">{{ object.content | safe }}</p>





        </div>
    </div>
</div>
{% endblock content %}